Repository treehouses/treehouses.github.io, pull requests merged in 2020-03, with the labels that each got.

#452 create William-Ward.md
  pages/vi/profiles/William-Ward.md
Labels: done

#455 templates: add spaces before headers (fixes #434)
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: done

#464 add periods in firststeps (fixes #446)
  pages/vi/firststeps.md
Labels: done, spelling/semantics

#468 update sshpi.md (fixes #466)
  pages/vi/sshpi.md
Labels: done, spelling/semantics

#470 helpful links add vagrant cheatsheet vagranttutorial.md (fixes #469)
  pages/vi/vagranttutorial.md
Labels: documentation, done

#472 update vagranttutorial.md (fixes #471)
  pages/vi/vagranttutorial.md
Labels: bug

#474 update sshpi.md (fixes #473)
  pages/vi/sshpi.md
Labels: documentation, done
