Repository treehouses/treehouses.github.io, pull requests merged in 2020-01, with the labels that each got.

#361 update download.md (fixes #360)
  pages/download.md
Labels: documentation

#354 create engherery.md
  pages/vi/profiles/engherery.md
Labels: done

#362 step7 alternative command (fixes #301)
  pages/vi/nextcloud-tor.md
Labels: done

#363 update download.md (fixes #364)
  pages/download.md
Labels: done

#334 team pictures added (fixes #333)
  pages/vi/retiredinterns.md
  pages/vi/team.md
Labels: in review

#368 update firststeps.md (fixes #367)
  pages/vi/firststeps.md
Labels: in review

#366 add 20200110-androidstudiosetup.md (fixes #365)
  pages/blog/20200110-androidstudiosetup.md
  pages/blog/images/20200105-android-studio.png
  pages/blog/images/20200105-avd-manager.png
  pages/blog/images/20200105-build-config.png
  pages/blog/images/20200105-gradle-folder.png
  pages/blog/images/20200105-green-checks.png
  pages/blog/images/20200105-import-project.png
  pages/blog/images/20200105-run-apk.png
  pages/blog/images/2020105-select-gradle.png
  pages/blog/list.md
Labels: in review

#374 profiles clean up (fixes #373)
  pages/vi/profiles/btdow.md
  pages/vi/profiles/gk-web.md
  pages/vi/profiles/jay-jhanji.md
  pages/vi/profiles/jingtu87.md
  pages/vi/profiles/jpadilla9.md
  pages/vi/profiles/kajanajustin.md
  pages/vi/profiles/rkoepke.md
  pages/vi/profiles/sabe-lab.md
  pages/vi/profiles/surferjreb.md
  pages/vi/profiles/trajper.md
  pages/vi/profiles/utsavgoswami.md
Labels: wontfix
