Repository treehouses/treehouses.github.io, pull requests merged in 2020-04, with the labels that each got.

#495 update team.md
  pages/vi/team.md
Labels: blocked, ready for interview

#528 update team.md
  pages/vi/team.md
Labels: blocked

#539 update team.md
  pages/vi/team.md
Labels: blocked

#560 update sshpi.md (fixes #475)
  pages/vi/sshpi.md
Labels: done
