Repository treehouses/treehouses.github.io, pull requests merged in 2020-02, with the labels that each got.

#403 step9 improve instructions (fixes #400)
  pages/vi/firststeps.md
  pages/vi/profiles/evoong.md
Labels: WIP

#408 Finding ip issue (fixes issue #405)
  pages/vi/find-pi.md
Labels: documentation, enhancement

#407 Step 5 issue (fixes #404)
  pages/vi/gitrepositories.md
Labels: spelling/semantics

#411 Fixed faulty first steps link: fixes #406
  pages/chat.md
Labels: bug, done

#410 perusal period (fixes #409)
  pages/vi/gitrepositories.md
Labels: done, spelling/semantics

#420 update team.md (fixes #419)
  pages/vi/team.md
Labels: bug, done

#417 update githubandmarkdown.md (fixes #416)
  pages/vi/githubandmarkdown.md
Labels: documentation, done, enhancement

#425 Update orientation.md (fixes #423)
  pages/vi/orientation.md
Labels: spelling/semantics

#422 update issue templates (fixes #421)
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: done, enhancement, in review
