Repository treehouses/treehouses.github.io, pull requests merged in 2020-08, with the labels that each got.

#692 create gautamsethi1.md
  pages/vi/profiles/gautamsethi1.md
Labels: in review

#676 update github-issues.md (fixes #674)
  pages/vi/github-issues.md
Labels: ready

#681 create "three" blogs
  pages/blog/20200724-cliandremote.md
  pages/blog/20200724-newdockerservice.md
  pages/blog/20200724-treehousescomponents.md
  pages/blog/images/20200724-android-studio-fragments.png
  pages/blog/images/20200724-android-studio-log.png
  pages/blog/images/20200724-android-studio-run.png
  pages/blog/images/20200724-code-climate-issues.png
  pages/blog/images/20200724-docker-ps.png
  pages/blog/images/20200724-docker-snippet.png
  pages/blog/images/20200724-grocy-login.png
  pages/blog/images/20200724-grocy.png
  pages/blog/images/20200724-remote-menu.png
  pages/blog/images/20200724-remote-services.png
  pages/blog/images/20200724-travis-ci.png
  pages/blog/list.md
Labels: done

#496 create 20200408-dockerfile.md
  pages/blog/20200408-dockerfile.md
  pages/blog/images/20200409-turtle1.png
  pages/blog/images/20200409-turtle2.png
  pages/blog/images/20200409-turtle3.png
  pages/blog/list.md
Labels: WIP
